spring:
  application:
    name: user-auth-service
  config:
    import: optional:configserver:http://config-server:8888
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "1"
      retries: 3
      properties:
        spring.json.add.type.headers: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

jwt:
  secret: 

resilience4j.ratelimiter:
  instances:
    login:
      limitForPeriod: 5
      limitRefreshPeriod: 5m
      timeoutDuration: 0

eureka:
  client:
    restclient:
      enabled: true
