spring:
  application:
    name: user-auth-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "1"
      retries: 3
      properties:
        spring.json.add.type.headers: false  # Không gửi type header để consumer không bị ràng buộc class

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

resilience4j.ratelimiter:
  instances:
    login:
      limitForPeriod: 5
      limitRefreshPeriod: 5m
      timeoutDuration: 0
