spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888 # Cập nhật để trỏ đến tên dịch vụ trong Docker Compose

server:
  port: 8889
resilience4j:
  ratelimiter:
    instances:
      login:
        limitForPeriod: 5
        limitRefreshPeriod: 5m
        timeoutDuration: 0
