spring:
  application:
    name: wallet-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: wallet-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer được override bởi KafkaConsumerConfig bean
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}
