server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_db
    username: root
    password: admin123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
redis:
  port: 6378
  url: localhost
logging:
  level:
    root: info
  file:
    name: D:\WorkSpace\Project\FPM-2025\log\wallet.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
grpc:
  server:
    port: 9091
    security:
      enabled: true
      certificateChain: classpath:certs/server.crt
      privateKey: classpath:certs/server.key
    keep-alive-time: 5s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      grpc.port: ${grpc.server.port}